-- Criar registro inicial do evento 2026 no Supabase
-- Execute este SQL no Supabase SQL Editor

-- Inserir evento do ano 2026
INSERT INTO events (
  year, 
  edition, 
  race_date, 
  age_cutoff_date, 
  location, 
  city, 
  state, 
  total_prize, 
  registrations_open,
  registration_open_date,
  registration_close_date,
  contact_email,
  contact_phone,
  social_instagram,
  social_facebook,
  start_time_10k,
  start_time_2k,
  slots_geral,
  slots_morador,
  slots_60plus,
  slots_infantil,
  price_geral
) VALUES (
  2026, 
  51, 
  '2026-06-24', 
  '2026-12-31', 
  'Praça da Matriz', 
  'Macuco', 
  'RJ', 
  15000, 
  true,
  '2025-12-01',
  '2026-06-20',
  'contato@corridamacuco.com.br',
  '(22) 99999-9999',
  '@corridamacuco',
  'corridamacuco',
  '07:00',
  '08:30',
  500,
  200,
  100,
  300,
  20.00
) ON CONFLICT (year) DO UPDATE SET
  edition = EXCLUDED.edition,
  race_date = EXCLUDED.race_date,
  age_cutoff_date = EXCLUDED.age_cutoff_date,
  location = EXCLUDED.location,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  total_prize = EXCLUDED.total_prize,
  registrations_open = EXCLUDED.registrations_open,
  registration_open_date = EXCLUDED.registration_open_date,
  registration_close_date = EXCLUDED.registration_close_date,
  contact_email = EXCLUDED.contact_email,
  contact_phone = EXCLUDED.contact_phone,
  social_instagram = EXCLUDED.social_instagram,
  social_facebook = EXCLUDED.social_facebook,
  start_time_10k = EXCLUDED.start_time_10k,
  start_time_2k = EXCLUDED.start_time_2k,
  slots_geral = EXCLUDED.slots_geral,
  slots_morador = EXCLUDED.slots_morador,
  slots_60plus = EXCLUDED.slots_60plus,
  slots_infantil = EXCLUDED.slots_infantil,
  price_geral = EXCLUDED.price_geral;

-- Verificar se foi criado
SELECT * FROM events WHERE year = 2026;
